# Dapr Kafka pub/sub component configuration for Kubernetes
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: todo-app
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka-cluster-kafka-bootstrap.kafka:9092"
    - name: consumerGroup
      value: "taskai-services"
    - name: authType
      value: "none"
    - name: initialOffset
      value: "oldest"
    - name: maxMessageBytes
      value: "1048576"
