# Dapr subscription for reminders topic (Kubernetes)
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: reminders-subscription
  namespace: todo-app
spec:
  pubsubname: kafka-pubsub
  topic: reminders
  routes:
    default: /api/reminders/handle
scopes:
  - taskai-notification-service
