# Dapr Subscription for Reminder Events
# Routes reminder events to the Notification Service
# Note: In v2alpha1, scopes are not supported. All apps with dapr.io/enabled will receive events.
# Filtering is done at the application level in /api/reminders/handle endpoint.

apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: reminders-subscription
  namespace: todo-app
spec:
  pubsubname: kafka-pubsub
  topic: reminders
  routes:
    default: /api/reminders/handle
