# Dapr Kafka pub/sub component configuration for Docker Compose
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka:9092"
    - name: consumerGroup
      value: "taskai-services"
    - name: authType
      value: "none"
    - name: initialOffset
      value: "oldest"
    - name: maxMessageBytes
      value: "1048576"
