# [Task]: Cloud-Native Implementation
# [Description]: Dapr PostgreSQL state store for DigitalOcean Managed PostgreSQL
# [Prerequisites]:
#   1. Create DigitalOcean Managed PostgreSQL cluster
#   2. Create database 'todo_chatbot' in the cluster
#   3. Create Kubernetes secret with credentials (see template below)

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: todo-app
spec:
  type: state.postgresql
  version: v1
  metadata:
    # Connection string from secret
    - name: connectionString
      secretKeyRef:
        name: database-credentials
        key: connection-string

    # Table name for Dapr state storage
    - name: tableName
      value: "dapr_state"

    # Key prefix for namespacing
    - name: keyPrefix
      value: "todo-chatbot"

    # Enable actor state store (if using Dapr actors)
    - name: actorStateStore
      value: "false"

    # Metadata table name (for transaction support)
    - name: metadataTableName
      value: "dapr_metadata"

    # Timeout for queries
    - name: timeout
      value: "30s"

    # Connection pool settings
    - name: maxConns
      value: "10"
    - name: maxIdleConns
      value: "5"
    - name: connMaxLifetime
      value: "30m"
    - name: connMaxIdleTime
      value: "15m"

---
# Secret template for DigitalOcean Managed PostgreSQL credentials
#
# IMPORTANT: Create this secret with your actual credentials BEFORE deployment:
#
# Using kubectl:
#   kubectl create secret generic database-credentials \
#     --from-literal=username="doadmin" \
#     --from-literal=password="<your-password>" \
#     --from-literal=host="private-db-postgresql-<region>-<id>-do-user-<user-id>-0.db.ondigitalocean.com" \
#     --from-literal=connection-string="postgresql://doadmin:<password>@private-db-postgresql-<region>-<id>-do-user-<user-id>-0.db.ondigitalocean.com:25060/todo_chatbot?sslmode=require" \
#     -n todo-app
#
# Or get connection details from:
#   doctl databases connection <database-id> --format Host,Port,User,Password,Database
#
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials-template
  namespace: todo-app
  annotations:
    description: "Template only - replace with actual DigitalOcean PostgreSQL credentials"
    do-not-apply: "true"
type: Opaque
stringData:
  # Get these from DigitalOcean Console -> Databases -> Your PostgreSQL Cluster -> Connection Details
  username: "doadmin"
  password: "your-postgres-password-from-digitalocean"
  host: "private-db-postgresql-nyc1-xxxxx-do-user-xxxxx-0.db.ondigitalocean.com"
  # Connection string format for DigitalOcean Managed PostgreSQL
  # Note: Port 25060 is the default for DigitalOcean Managed PostgreSQL
  # Note: sslmode=require is mandatory
  connection-string: "postgresql://doadmin:your-password@private-db-postgresql-nyc1-xxxxx-do-user-xxxxx-0.db.ondigitalocean.com:25060/todo_chatbot?sslmode=require"
